# Implementation migrated from cpg_chunker.py
import json
import os
import logging
import tempfile
import shutil
import subprocess
from typing import List, Dict, Any
from langchain_core.documents import Document
from .chunker_interface import ChunkerInterface

logger = logging.getLogger(__name__)

class CpgCodeChunker(ChunkerInterface):
    """
    A semantic chunker for Java code that uses Code Property Graphs (CPGs)
    generated by the `joern` tool.
    """

    def __init__(self):
        if not shutil.which("joern"):
            raise ImportError(
                "The 'joern' command-line tool is not installed or not in the system's PATH. "
                "Please install joern from https://joern.io to use the CPG chunking strategy."
            )

    def chunk_documents(self, documents: List[Document]) -> List[Document]:
        with tempfile.TemporaryDirectory() as temp_dir:
            for doc in documents:
                source_path = doc.metadata.get("source", "unknown/file.java")
                sanitized_path = os.path.normpath(source_path).lstrip(os.path.sep)
                drive, tail = os.path.splitdrive(sanitized_path)
                sanitized_path = tail.lstrip(os.path.sep)
                doc_path = os.path.join(temp_dir, sanitized_path)
                os.makedirs(os.path.dirname(doc_path), exist_ok=True)
                with open(doc_path, "w", encoding="utf-8") as f:
                    f.write(doc.page_content)

            cpg_json_path = os.path.join(temp_dir, "cpg.json")
            self._run_joern_process(temp_dir, cpg_json_path)

            if not os.path.exists(cpg_json_path):
                logger.warning("joern did not produce a CPG file after export. Falling back to basic chunking.")
                return documents

            with open(cpg_json_path, "r", encoding="utf-8") as f:
                cpg_data = json.load(f)

            return self._create_chunks_from_cpg(documents, cpg_data)

    def _run_joern_process(self, input_path: str, output_path: str):
        logger.info(f"Running joern process for directory: {input_path}")
        joern_commands = [
            f'importCode("{input_path}")',
            'run.ossdataflow',
            f'exportCpg(filename="{output_path}", repr="json")',
            'delete'
        ]
        command_input = "\n".join(joern_commands) + "\n"
        command = ["joern"]
        command_timeout = 600
        try:
            result = subprocess.run(
                command,
                input=command_input,
                check=True,
                capture_output=True,
                text=True,
                timeout=command_timeout
            )
            logger.info("joern process (import, analyze, export) complete.")
            if result.stderr:
                logger.debug(f"--- joern stderr ---\n{result.stderr}")
        except subprocess.TimeoutExpired:
            logger.error(f"Joern process timed out after {command_timeout} seconds.", exc_info=True)
            raise RuntimeError("Joern process timed out.")
        except subprocess.CalledProcessError as e:
            logger.error("Joern command failed.", exc_info=True)
            logger.error(f"Command: {' '.join(command)}")
            logger.error(f"Input: {command_input}")
            logger.error(f"Stdout: {e.stdout}")
            logger.error(f"Stderr: {e.stderr}")
            raise RuntimeError("Failed to generate CPG with joern.")

    def _build_call_graph(self, method_nodes: Dict[int, Any], all_nodes: Dict[int, Any], edges: List[Dict[str, Any]]) -> Dict[int, Dict[str, set]]:
        call_graph = {node_id: {'calls': set(), 'called_by': set()} for node_id in method_nodes}
        for edge in edges:
            if edge.get('label') == 'CALL' and edge['outV'] in method_nodes and edge['inV'] in method_nodes:
                caller_id = edge['outV']
                callee_id = edge['inV']
                call_graph[caller_id]['calls'].add(all_nodes[callee_id]['properties']['fullName'])
                call_graph[callee_id]['called_by'].add(all_nodes[caller_id]['properties']['fullName'])
        return call_graph

    def _create_chunks_from_cpg(self, documents: List[Document], cpg_data: Dict[str, Any]) -> List[Document]:
        all_nodes = {node['id']: node for node in cpg_data.get('nodes', [])}
        edges = cpg_data.get('edges', [])
        method_nodes = {node_id: node for node_id, node in all_nodes.items() if node.get('label') == 'METHOD'}
        call_graph = self._build_call_graph(method_nodes, all_nodes, edges)
        all_chunks = []
        doc_map = {doc.metadata['source']: doc for doc in documents}
        for method_id, method_node in method_nodes.items():
            props = method_node.get('properties', {})
            file_name = props.get('filename', 'N/A')
            if file_name not in doc_map or not props.get('code'):
                continue
            original_doc = doc_map[file_name]
            method_code = props['code']
            context_lines = []
            calls = call_graph[method_id]['calls']
            called_by = call_graph[method_id]['called_by']
            if calls:
                context_lines.append(f"// This method calls: {', '.join(sorted(list(calls)))}")
            if called_by:
                context_lines.append(f"// This method is called by: {', '.join(sorted(list(called_by)))}")
            context_header = "\n".join(context_lines)
            chunk_content = f"{context_header}\n{method_code}" if context_header else method_code
            metadata = original_doc.metadata.copy()
            metadata.update({
                "cpg_method_name": props.get('fullName'),
                "cpg_signature": props.get('signature'),
                "start_line": props.get('lineNumber'),
                "end_line": props.get('lineNumberEnd'),
            })
            all_chunks.append(Document(page_content=chunk_content, metadata=metadata))
        if not all_chunks:
            logger.warning("CPG chunker did not find any methods. Returning original documents.")
            return documents
        return all_chunks
# Moved from cpg_chunker.py
# Implementation of CpgCodeChunker
